### ISSUE TITLE
Does not run on Arch Linux

### ISSUE THREAD

**Issue by Tea23** [Amadren/lgogd_uri-mk.II#1]
I'm investigating packaging this for Arch, as I do for lgogdownloader itself.

Upon running it I get a window telling me a 'programming error has occurred' with the following info:

```
Traceback (most recent call last):
  File "/usr/bin/lgogd_uri", line 9, <module>()
        sys.exit(
            load_entry_point('lgogd-uri===MK.II', 'gui_scripts', 'lgogd_uri')()
        )
  variables: {  'load_entry_point': (  'local',
                          <function load_entry_point at 0x7f1ef3506ed8>)}
  File "/usr/lib/python2.7/site-packages/lgogd_uri/main.py", line 511, main()
        app.start(vars(opts), args, int(time.time()))
        if app.is_running():
  variables: {  'app.start': (  'local',
                   <bound method Application.start of <lgogd_uri.main.Application at / at 0x7f1ee91ab090>>),
   'args': ('local', None),
   'int': ('builtin', <type 'int'>),
   'opts': ('local', <Values at 0x7f1ee91a4950: {'verbose': 3, 'quiet': 0}>),
   'time.time': ('global', <built-in function time>),
   'vars': ('builtin', <built-in function vars>)}
  File "/usr/lib/python2.7/site-packages/lgogd_uri/main.py", line 472, start(self=<lgogd_uri.main.Application at />, options={'quiet': 0, 'verbose': 3}, arguments=[], timestamp=1463949626)
                self.running = True
                self._init_gui()
                self.enqueue_uris(arguments)
  variables: {  'self._init_gui': (  'local',
                        <bound method Application._init_gui of <lgogd_uri.main.Application at / at 0x7f1ee91ab090>>)}
  File "/usr/lib/python2.7/site-packages/lgogd_uri/main.py", line 202, _init_gui(self=<lgogd_uri.main.Application at />)
            # Prepare a libnotify notification we can reuse
            if notify and notify.init("lgogd_uri"):
                self.notification = notify.Notification("GOG Downloads Complete",
  variables: {  'notify': (  'global',
                <module 'notify2' from '/usr/lib/python2.7/site-packages/notify2.pyc'>),
   'notify.init': ('global', <function init at 0x7f1ee919a500>)}
  File "/usr/lib/python2.7/site-packages/notify2.py", line 96, init(app_name=u'lgogd_uri', mainloop=None)
        dbus_obj = bus.get_object('org.freedesktop.Notifications',
                                  '/org/freedesktop/Notifications')
        dbus_iface = dbus.Interface(dbus_obj,
  File "/usr/lib/python2.7/site-packages/dbus/bus.py", line 241, get_object(self=<dbus._dbus.SessionBus (session)>, bus_name='org.freedesktop.Notifications', object_path='/org/freedesktop/Notifications', introspect=True, follow_name_owner_changes=False, **kwargs={})
                                         introspect=introspect,
                                         follow_name_owner_changes=follow_name_owner_changes)
  variables: {  'follow_name_owner_changes': ('local', None)}
  File "/usr/lib/python2.7/site-packages/dbus/proxies.py", line 248, __init__(self=<ProxyObject wrapping <dbus._dbus.SessionBus (se...top.Notifications /org/freedesktop/Notifications>, conn=<dbus._dbus.SessionBus (session)>, bus_name='org.freedesktop.Notifications', object_path='/org/freedesktop/Notifications', introspect=True, follow_name_owner_changes=False, **kwargs={})
            if not follow_name_owner_changes:
                self._named_service = conn.activate_name_owner(bus_name)
  variables: {  'bus_name': ('local', 'org.freedesktop.Notifications'),
   'conn.activate_name_owner': (  'local',
                                  <bound method SessionBus.activate_name_owner of <dbus._dbus.SessionBus (session) at 0x7f1ee9189bf0>>),
   'self._named_service': ('local', 'org.freedesktop.Notifications')}
  File "/usr/lib/python2.7/site-packages/dbus/bus.py", line 180, activate_name_owner(self=<dbus._dbus.SessionBus (session)>, bus_name='org.freedesktop.Notifications')
                    # else it doesn't exist: try to start it
                    self.start_service_by_name(bus_name)
                    return self.get_name_owner(bus_name)
  variables: {  'bus_name': ('local', 'org.freedesktop.Notifications'),
   'self.start_service_by_name': (  'local',
                                    <bound method SessionBus.start_service_by_name of <dbus._dbus.SessionBus (session) at 0x7f1ee9189bf0>>)}
  File "/usr/lib/python2.7/site-packages/dbus/bus.py", line 278, start_service_by_name(self=<dbus._dbus.SessionBus (session)>, bus_name='org.freedesktop.Notifications', flags=0)
                                             'StartServiceByName',
                                             'su', (bus_name, flags)))
  variables: {  'bus_name': ('local', 'org.freedesktop.Notifications'),
   'flags': ('local', None)}
  File "/usr/lib/python2.7/site-packages/dbus/connection.py", line 651, call_blocking(self=<dbus._dbus.SessionBus (session)>, bus_name='org.freedesktop.DBus', object_path='/org/freedesktop/DBus', dbus_interface='org.freedesktop.DBus', method='StartServiceByName', signature='su', args=('org.freedesktop.Notifications', 0), timeout=-1.0, byte_arrays=False, **kwargs={})
            reply_message = self.send_message_with_reply_and_block(
                message, timeout)
            args_list = reply_message.get_args_list(**get_args_opts)
  variables: {  'message': (  'local',
                 <dbus.lowlevel.MethodCallMessage path: /org/freedesktop/DBus, iface: org.freedesktop.DBus, member: StartServiceByName dest: org.freedesktop.DBus>),
   'timeout': ('local', -1.0)}
DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Notifications was not provided by any .service files
```

Not sure if this is because of a lack of dependencies or something else. There are no dependencies listed anywhere on the github page, frustratingly enough but I have `python2-notify2` and `pygtk` installed, which as far as I can tell are the only deps aside from `python2` itself.

**Comment by Amadren** [comment]
Here are the required dependencies on Debian/Ubuntu:
python-gtk2 python-dbus python-vte python-notify python-pip

Unfortunately, I have no arch install right now... I'll install it asap and try to fix this problem.
